# Generated by Django 5.2.8 on 2026-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_tag_answer_attachment_question_accepted_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='1~20 (가로4×세로5)', unique=True)),
                ('image', models.FileField(help_text='GIF/PNG/JPG (400×50px 권장)', upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='클릭 시 이동할 URL (선택)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
