# Generated by Django 6.0.3 on 2026-03-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_alter_answer_id_alter_category_id_alter_comment_id_and_more'),
        ('pybo', '0010_banner'),
    ]

    operations = [
    ]
